# -----------------------------------------------------------------------
# Travel Agent Jake: "Find Your Perfect Ski Resort" quiz
# -----------------------------------------------------------------------
# Original quiz, inspired by the general "personality quiz" format used by
# big ski operators, but every question, answer, persona name, persona
# description and resort write-up below is written fresh for Jake. No
# text is copied from any other source. Resort names, piste stats, lift
# counts and altitudes are plain facts (researched from official resort
# sites and public ski-resort data sites) and are not owned by anyone.
#
# HOW IT SCORES: each of the 10 main questions has 5 answers, tagged A-E.
# Track how many of each letter the user picks; whichever letter has the
# highest count wins, and that letter's persona is the result.
#
# BUDGET TESTER: after the 10 scored questions, a separate budget question
# (low/mid/high) is asked. It does NOT affect the persona, only which 3 of
# the persona's 5 resorts get shown, so a genuinely affordable pick surfaces
# for people who ask for one instead of every result skewing expensive.
#
# STYLE NOTE: no em dashes or en dashes anywhere in this copy (site-wide
# rule for travelagentjake.co.uk) -- use full stops, commas or colons instead.
# -----------------------------------------------------------------------

QUESTIONS = [
    {
        "question": "First things first, where are you sleeping?",
        "answers": {
            "A": "Ski-in, ski-out. I want my boots on and I'm on the lift.",
            "B": "Somewhere with easy access to off-piste and the backcountry.",
            "C": "Right in the middle of town, close to the bars.",
            "D": "Somewhere quiet with a proper spa and a view.",
            "E": "A little family-run place where the owner knows everyone's name.",
        },
    },
    {
        "question": "How's the day starting?",
        "answers": {
            "A": "Straight out the door, first lift, no faffing.",
            "B": "Checking the off-piste conditions and route for the day.",
            "C": "Slowly. Last night went on a bit.",
            "D": "A proper sit-down breakfast, no rush at all.",
            "E": "Fresh pastries from the bakery down the road.",
        },
    },
    {
        "question": "It's 11am. Where are you on the mountain?",
        "answers": {
            "A": "As far across the ski area as I can physically get.",
            "B": "Off the marked runs, hunting fresh snow.",
            "C": "Already thinking about which bar does the best mulled wine.",
            "D": "Taking it slow, stopping for the views.",
            "E": "Wherever the food is good, I plan runs around lunch spots.",
        },
    },
    {
        "question": "Lunch. What's the move?",
        "answers": {
            "A": "Something quick so I can get back out there.",
            "B": "Wherever's closest to where I want to explore next.",
            "C": "A long one, with a drink or two.",
            "D": "A proper sit-down meal, no rush, mountain views.",
            "E": "A local mountain hut with food I can't get at home.",
        },
    },
    {
        "question": "What's genuinely non-negotiable on this trip?",
        "answers": {
            "A": "Miles. I want to have skied the whole area by the end.",
            "B": "At least one day doing something other than piste skiing.",
            "C": "A big night out, at least once.",
            "D": "Proper downtime. This is a holiday, not a bootcamp.",
            "E": "Trying the local food and drink, not just the resort menu.",
        },
    },
    {
        "question": "What does 4pm look like?",
        "answers": {
            "A": "Squeezing in one more run before the lifts close.",
            "B": "Still out there, well after everyone else has stopped.",
            "C": "Straight into après, ski boots and all.",
            "D": "Back at the hotel, into the hot tub.",
            "E": "Sat somewhere warm with a snack, watching the world go by.",
        },
    },
    {
        "question": "Be honest, what's the evening actually about?",
        "answers": {
            "A": "An early night. Tomorrow's a big ski day.",
            "B": "Whatever's next on the list: ice driving, snowmobiling, anything.",
            "C": "Wherever the night takes us, honestly.",
            "D": "A good dinner and bed, no drama.",
            "E": "A proper meal somewhere that isn't in the hotel.",
        },
    },
    {
        "question": "How's your kit looking by day 3?",
        "answers": {
            "A": "Everything's been used, hard, every single day.",
            "B": "A bit muddy and a lot more adventurous than when I arrived.",
            "C": "Slightly worse for wear, much like me.",
            "D": "Barely touched. Half my case was loungewear anyway.",
            "E": "Fine, I've spent as much time eating as skiing.",
        },
    },
    {
        "question": "What will you actually be posting about?",
        "answers": {
            "A": "The stats: km skied, vertical drop, the lot.",
            "B": "The one moment that scared me a bit, in a good way.",
            "C": "That video from the bar everyone will deny being in.",
            "D": "The view from the hot tub. Every time.",
            "E": "Whatever I ate. Always the food.",
        },
    },
    {
        "question": "Last one, what's already on the list for next time?",
        "answers": {
            "A": "A bigger resort. More terrain, more miles.",
            "B": "Heli-skiing. It's happening eventually.",
            "C": "Somewhere with an even bigger reputation for nightlife.",
            "D": "The same again, please. Don't change a thing.",
            "E": "Somewhere I've never tried the food before.",
        },
    },
]

# Not scored into the A-E tally, used only to pick which 3 of the 5
# matched resorts to surface (see build.py), so budget options genuinely
# show up rather than every result skewing towards the priciest resorts.
BUDGET_QUESTION = {
    "question": "Last thing, what's the ski budget looking like?",
    "answers": {
        "low": "Keep it affordable. I still want a proper week on snow, just without the big price tag.",
        "mid": "Good value matters, but I'm not counting every penny.",
        "high": "Whatever it costs. I'm not really looking at the price.",
    },
}

PERSONAS = {
    "A": {
        "name": "The Piste Chaser",
        "tagline": "You're here to ski. All of it.",
        "description": "You measure a trip in vertical metres, not lie-ins. Big, joined-up terrain matters more to you than nightlife or spa days, and you want to ski every corner of the map before the lifts shut.",
        "resorts": [
            {
                "name": "Val Thorens, France",
                "budget": "high",
                "blurb": "The highest resort in Europe, and part of the Three Valleys, the biggest linked ski area there is. You will run out of daylight before you run out of pistes.",
                "piste_km": 150,
                "runs_green": 11,
                "runs_blue": 29,
                "runs_red": 29,
                "runs_black": 9,
                "lifts": 29,
                "altitude_top_m": 3230,
                "altitude_base_m": 2300,
                "things_to_do": ["Aquamotion aquatic centre: slides, wave pool, spa and Nordic baths", "La Bee toboggan/luge run and the illuminated ice grotto", "Snowmobile safaris and dog-sledding excursions above the resort"],
                "official_url": "https://www.valthorens.com/en/",
                "best_for": "Snow-sure high-altitude skiing, groups of friends and lively apres-ski",
            },
            {
                "name": "Whistler Blackcomb, Canada",
                "budget": "high",
                "blurb": "Two enormous mountains joined by a gondola, with more marked runs than most people could ski in a fortnight.",
                "piste_km": 200,
                "runs_green": 40,
                "runs_blue": 110,
                "runs_red": 0,
                "runs_black": 50,
                "lifts": 37,
                "altitude_top_m": 2284,
                "altitude_base_m": 675,
                "things_to_do": ["Scandinave Spa Whistler outdoor hydrotherapy circuit", "Vallea Lumina night-time light and sound forest walk", "PEAK 2 PEAK Gondola ride between Whistler and Blackcomb summits, plus the Whistler Village Stroll for shopping and nightlife"],
                "official_url": "https://www.whistlerblackcomb.com/",
                "best_for": "Groups of friends, expert/off-piste skiers and anyone wanting North America's biggest resort",
            },
            {
                "name": "Sölden, Austria",
                "budget": "mid",
                "blurb": "Big, snow-sure and joined across two glaciers, ideal if you want to clock serious mileage without worrying about the snow running out.",
                "piste_km": 146,
                "runs_green": 20,
                "runs_blue": 30,
                "runs_red": 22,
                "runs_black": 3,
                "lifts": 31,
                "altitude_top_m": 3340,
                "altitude_base_m": 1350,
                "things_to_do": ["007 Elements James Bond cinematic installation on the Gaislachkogl summit", "Aqua Dome thermal spa and sauna world in nearby Längenfeld", "Ice Q restaurant with panoramic glacier views (as seen in Spectre)"],
                "official_url": "https://www.soelden.com/en/",
                "best_for": "Confident intermediates, groups of friends and glacier skiing early/late season",
            },
            {
                "name": "Les Deux Alpes, France",
                "budget": "mid",
                "blurb": "One of the highest lift-served glaciers in Europe, so you can ski right through summer conditions and rack up serious vertical without worrying about the snow holding up.",
                "piste_km": 220,
                "runs_green": 25,
                "runs_blue": 25,
                "runs_red": 30,
                "runs_black": 15,
                "lifts": 40,
                "altitude_top_m": 3523,
                "altitude_base_m": 1280,
                "things_to_do": ["Toboggan/luge run and the Diable au Coeur mountain-top restaurant zipline area", "La Chalcedoine spa and wellness centre in the village", "Summer glacier snowboard/freestyle park and the resort's lively main-street nightlife strip"],
                "official_url": "https://www.les2alpes.com/en/",
                "best_for": "Groups of friends, snowboarders/freestylers and nightlife-seekers",
            },
            {
                "name": "Bansko, Bulgaria",
                "budget": "low",
                "blurb": "Bulgaria's biggest ski area, and proof that big mileage doesn't have to mean a big price tag. Wide, well-groomed pistes and lift queues you can actually live with.",
                "piste_km": 75,
                "runs_green": 8,
                "runs_blue": 13,
                "runs_red": 5,
                "runs_black": 2,
                "lifts": 14,
                "altitude_top_m": 2560,
                "altitude_base_m": 990,
                "things_to_do": ["Bansko's cobbled old town Pirin Street: bars, mehanas (taverns) and nightlife", "Thermal mineral spa pools at nearby Banya village", "Snowmobile tours and horse-drawn sleigh rides through the pine forests"],
                "official_url": "https://www.banskoski.com/",
                "best_for": "Budget-conscious groups, beginners and families",
            },
        ],
    },
    "B": {
        "name": "The Powder Hunter",
        "tagline": "The piste map is just a suggestion.",
        "description": "Marked runs are where you start the day, not where you finish it. You're happiest off-piste, trying something new, and coming home with a story that starts with 'so this was a bit terrifying...'",
        "resorts": [
            {
                "name": "Chamonix, France",
                "budget": "high",
                "blurb": "Legendary off-piste at the foot of Mont Blanc, with guiding and touring options for pushing past the marked runs.",
                "piste_km": 151,
                "runs_green": 16,
                "runs_blue": 27,
                "runs_red": 25,
                "runs_black": 12,
                "lifts": 49,
                "altitude_top_m": 3842,
                "altitude_base_m": 1035,
                "things_to_do": ["Aiguille du Midi cable car and the glass-floored 'Step into the Void' skywalk", "Off-piste Vallée Blanche glacier descent with a mountain guide", "Chamonix's Rue du Docteur Paccard: restaurants, bars and mountaineering shops"],
                "official_url": "https://www.chamonix.com/",
                "best_for": "Expert and off-piste/freeride skiers, mountaineers",
            },
            {
                "name": "Verbier, Switzerland",
                "budget": "high",
                "blurb": "Some of the best freeride terrain in the Alps, plus heli-skiing if you want to go all in.",
                "piste_km": 412,
                "runs_green": 20,
                "runs_blue": 55,
                "runs_red": 45,
                "runs_black": 12,
                "lifts": 68,
                "altitude_top_m": 3330,
                "altitude_base_m": 1350,
                "things_to_do": ["Farinet Lounge/Farm Club apres-ski and nightlife scene", "Freeride skiing off Mont-Fort and Mont-Gelé (birthplace of the Freeride World Tour)", "Verbier Sport Plus wellness centre with pool, spa and ice rink"],
                "official_url": "https://www.verbier.ch/en",
                "best_for": "Expert/off-piste skiers and groups of friends who like nightlife",
            },
            {
                "name": "Niseko, Japan",
                "budget": "high",
                "blurb": "Famous for the lightest, deepest powder going, and a backcountry scene that draws serious skiers from all over the world.",
                "piste_km": 51,
                "runs_green": 15,
                "runs_blue": 13,
                "runs_red": 6,
                "runs_black": 4,
                "lifts": 32,
                "altitude_top_m": 1188,
                "altitude_base_m": 255,
                "things_to_do": ["Onsen (hot spring) bathing, e.g. Yukoro Onsen or the resort's hotel onsens", "Night skiing under floodlights across Grand Hirafu and Hanazono", "Backcountry/tree-run powder skiing and Niseko Village's izakaya restaurant strip"],
                "official_url": "https://www.niseko.ne.jp/en/",
                "best_for": "Powder-hunters, groups of friends and Japanese-culture-curious couples",
            },
            {
                "name": "Passo Tonale, Italy",
                "budget": "mid",
                "blurb": "Wide open bowls, a glacier at the top, and some of the best-value off-piste access in the Alps. Less crowded than the big names, with terrain that rewards exploring.",
                "piste_km": 100,
                "runs_green": 10,
                "runs_blue": 25,
                "runs_red": 20,
                "runs_black": 5,
                "lifts": 29,
                "altitude_top_m": 3000,
                "altitude_base_m": 1121,
                "things_to_do": ["Presena Glacier skiing and the Passo Tonale WWI open-air museum trail", "Family-friendly toboggan run and snow-tubing park", "Spa and wellness centre at one of the resort's hotels, plus the compact village's ski-in/ski-out nightlife strip"],
                "official_url": "https://www.visittonale.com/en/",
                "best_for": "Families and beginners/early intermediates",
            },
            {
                "name": "Jasná, Slovakia",
                "budget": "low",
                "blurb": "The Tatras' best-kept secret. Genuinely varied terrain and proper backcountry pockets, at a fraction of what you'd pay for the same adventure further west.",
                "piste_km": 52,
                "runs_green": 10,
                "runs_blue": 12,
                "runs_red": 8,
                "runs_black": 1,
                "lifts": 20,
                "altitude_top_m": 2004,
                "altitude_base_m": 943,
                "things_to_do": ["Aquapark Tatralandia water and thermal park in nearby Liptovský Mikuláš", "Freeride zones and off-piste bowls beneath Chopok's summit", "Demänovská Cave of Liberty ice/cave system and the resort's mountain-hut restaurants"],
                "official_url": "https://www.jasna.sk/en",
                "best_for": "Families and budget-conscious groups/beginners",
            },
        ],
    },
    "C": {
        "name": "The Après Legend",
        "tagline": "Skiing is just the warm-up.",
        "description": "You're here for the whole holiday, not just the mountain, and for you that means the bars, the bands, and the walk of shame back to the hotel still in your ski boots.",
        "resorts": [
            {
                "name": "St Anton am Arlberg, Austria",
                "budget": "high",
                "blurb": "The spiritual home of après-ski. The parties start on the mountain and don't really stop.",
                "piste_km": 130,
                "runs_green": 8,
                "runs_blue": 25,
                "runs_red": 35,
                "runs_black": 12,
                "lifts": 41,
                "altitude_top_m": 2811,
                "altitude_base_m": 1300,
                "things_to_do": ["MooserWirt and Krazy Kanguruh: Europe's most famous apres-ski bars", "Off-piste ski touring and the legendary Valluga freeride terrain", "Arlberg-well.com spa and wellness centre in the village"],
                "official_url": "https://www.stantonamarlberg.com/en",
                "best_for": "Expert/off-piste skiers and groups of friends who like a big apres-ski scene",
            },
            {
                "name": "Mayrhofen, Austria",
                "budget": "mid",
                "blurb": "A proper party resort with a young, lively crowd and bars that get going the second the lifts close.",
                "piste_km": 139,
                "runs_green": 12,
                "runs_blue": 22,
                "runs_red": 27,
                "runs_black": 3,
                "lifts": 58,
                "altitude_top_m": 2500,
                "altitude_base_m": 630,
                "things_to_do": ["The Harakiri piste: one of the steepest marked runs in the Alps (78% gradient)", "Europahaus Mayrhofen spa, pool and wellness centre", "Snowbombing festival atmosphere and the village's busy apres-ski bars"],
                "official_url": "https://www.mayrhofen.at/en",
                "best_for": "Groups of friends/apres-ski crowds and intermediates",
            },
            {
                "name": "Ischgl, Austria",
                "budget": "high",
                "blurb": "Big-name concerts, big nights out, and skiing across the Austria-Switzerland border by day.",
                "piste_km": 200,
                "runs_green": 5,
                "runs_blue": 14,
                "runs_red": 42,
                "runs_black": 13,
                "lifts": 42,
                "altitude_top_m": 2900,
                "altitude_base_m": 1380,
                "things_to_do": ["Ischgl's famous season-opening/closing concerts and Kuhstall/Trofana Alm apres-ski bars", "Cross-border 'ski to Samnaun' run into Switzerland for duty-free shopping", "Silvretta Therme Ischgl spa and thermal baths"],
                "official_url": "https://www.ischgl.com/en",
                "best_for": "Intermediates, groups of friends and apres-ski/nightlife fans",
            },
            {
                "name": "Saalbach Hinterglemm, Austria",
                "budget": "mid",
                "blurb": "One giant, joined-up party circuit disguised as a ski area. The bars start filling from early afternoon and the whole valley is built for a big night.",
                "piste_km": 200,
                "runs_green": 6,
                "runs_blue": 31,
                "runs_red": 27,
                "runs_black": 6,
                "lifts": 52,
                "altitude_top_m": 2020,
                "altitude_base_m": 1000,
                "things_to_do": ["Ski Circus round trip linking Saalbach, Hinterglemm, Leogang and Fieberbrunn", "Baumbar Lounge and the Saalbach 'apres-ski mile' nightlife strip", "Alpine Coaster toboggan run and the Panorama Park scenic hiking/sledding trails"],
                "official_url": "https://www.saalbach.com/en",
                "best_for": "Groups of friends, intermediates and apres-ski/nightlife fans",
            },
            {
                "name": "Borovets, Bulgaria",
                "budget": "low",
                "blurb": "Cheap drinks, a lively strip, and a crowd that's there for a good time as much as the skiing. Your money goes a long way here, on and off the mountain.",
                "piste_km": 58,
                "runs_green": 3,
                "runs_blue": 11,
                "runs_red": 9,
                "runs_black": 4,
                "lifts": 11,
                "altitude_top_m": 2550,
                "altitude_base_m": 1320,
                "things_to_do": ["Borovets' lively apres-ski strip of bars and clubs at the resort centre", "Snowmobile safaris and quad-biking excursions in the Rila mountains", "Horse-drawn sleigh rides through the pine forest to mountain hut restaurants"],
                "official_url": "https://www.borovets-bg.com/",
                "best_for": "Budget-conscious groups of friends and beginners/families",
            },
        ],
    },
    "D": {
        "name": "The Slow Skier",
        "tagline": "It's a holiday. Act like it.",
        "description": "You'll ski, but you're not in a hurry, and you're definitely not missing a long lunch for one more run. Good food, a proper spa, and views worth stopping for matter just as much as the skiing.",
        "resorts": [
            {
                "name": "Courchevel, France",
                "budget": "high",
                "blurb": "Effortlessly smart, with the kind of restaurants and hotels that make lounging around feel entirely justified.",
                "piste_km": 150,
                "runs_green": 27,
                "runs_blue": 40,
                "runs_red": 42,
                "runs_black": 10,
                "lifts": 67,
                "altitude_top_m": 2740,
                "altitude_base_m": 1300,
                "things_to_do": ["Luxury boutique shopping street in Courchevel 1850 (Rue de l'Eglise)", "Aquamotion water park (shared with Val Thorens' network) and Courchevel's own spas/Michelin-starred restaurants", "Ice rink, dog-sledding and paragliding above the resort"],
                "official_url": "https://www.courchevel.com/en/",
                "best_for": "Luxury travellers, families and couples wanting a five-star experience",
            },
            {
                "name": "Lech am Arlberg, Austria",
                "budget": "high",
                "blurb": "Quietly luxurious, beautifully kept, and about as relaxed as skiing gets.",
                "piste_km": 110,
                "runs_green": 4,
                "runs_blue": 42,
                "runs_red": 40,
                "runs_black": 18,
                "lifts": 34,
                "altitude_top_m": 2810,
                "altitude_base_m": 1450,
                "things_to_do": ["Ski safari across the wider Arlberg lift network to Zürs and St Anton", "Rud-Alpe and other gourmet mountain-hut restaurants (Lech is known for fine dining)", "Vitaltherme spa in nearby Zürs/Lech village and upscale boutique shopping"],
                "official_url": "https://www.lechzuers.com/en",
                "best_for": "Couples, luxury travellers and confident intermediate/red-run skiers",
            },
            {
                "name": "Cortina d'Ampezzo, Italy",
                "budget": "high",
                "blurb": "Dramatic Dolomites scenery, excellent food, and a pace of life that never feels rushed.",
                "piste_km": 120,
                "runs_green": 10,
                "runs_blue": 42,
                "runs_red": 19,
                "runs_black": 8,
                "lifts": 37,
                "altitude_top_m": 2930,
                "altitude_base_m": 1220,
                "things_to_do": ["Rifugio Lagazuoi and other iconic mountain-hut lunches with Dolomites views", "Cortina's elegant Corso Italia: designer shopping and cafe culture", "Natural ice rink (former 1956 Winter Olympics venue) and the Faloria cable car viewpoint"],
                "official_url": "https://www.cortina.dolomiti.org/en",
                "best_for": "Couples, luxury travellers and intermediates who enjoy scenery and dining",
            },
            {
                "name": "Alpbach, Austria",
                "budget": "mid",
                "blurb": "One of Austria's prettiest villages, chocolate-box chalets and all, with gentle, well-groomed slopes that don't ask too much of you.",
                "piste_km": 145,
                "runs_green": 5,
                "runs_blue": 34,
                "runs_red": 13,
                "runs_black": 18,
                "lifts": 14,
                "altitude_top_m": 2030,
                "altitude_base_m": 1000,
                "things_to_do": ["Alpbach's traditional chocolate-box village centre: widely rated one of Austria's prettiest", "Toboggan/natural luge runs from the mountain restaurants back to the village", "Alpbachtal Card activities including the local swimming/spa centre and ice rink"],
                "official_url": "https://www.alpbachtal.at/en",
                "best_for": "Families and beginners/early intermediates",
            },
            {
                "name": "Pamporovo, Bulgaria",
                "budget": "low",
                "blurb": "Bulgaria's quietest, gentlest resort: forested, easy-going pistes and a properly relaxed pace, without the price tag of the Alps.",
                "piste_km": 37,
                "runs_green": 5,
                "runs_blue": 4,
                "runs_red": 7,
                "runs_black": 3,
                "lifts": 14,
                "altitude_top_m": 1931,
                "altitude_base_m": 1620,
                "things_to_do": ["Wolf's Jaw (Vълчи зъб) rock formation and forest walking/sledging trails", "Nearby Chepelare ski museum and the Perelik hotel spa/wellness centre", "Snowmobile and horse-sledge excursions through the pine forest"],
                "official_url": "https://www.pamporovo.bg/en/",
                "best_for": "Families and beginners; a gentle, low-altitude resort",
            },
        ],
    },
    "E": {
        "name": "The Food-First Skier",
        "tagline": "You plan runs around restaurants, not the other way round.",
        "description": "Skiing's great, but let's be honest, you're really here for the food. Mountain huts, local specialities and somewhere with a proper wine list will always win over another lap of the same run.",
        "resorts": [
            {
                "name": "Kitzbühel, Austria",
                "budget": "high",
                "blurb": "A genuinely beautiful old town with brilliant mountain restaurants scattered across the slopes.",
                "piste_km": 158,
                "runs_green": 10,
                "runs_blue": 22,
                "runs_red": 25,
                "runs_black": 13,
                "lifts": 30,
                "altitude_top_m": 2000,
                "altitude_base_m": 800,
                "things_to_do": ["The Streif: the world-famous Hahnenkamm downhill race course, skiable by strong intermediates when open", "Kitzbühel's medieval old town: boutique shopping and cafe/bar culture", "Aquarena Kitzbühel swimming and spa complex"],
                "official_url": "https://www.kitzski.at/en",
                "best_for": "Couples, groups of friends and confident intermediate skiers",
            },
            {
                "name": "Baqueira-Beret, Spain",
                "budget": "mid",
                "blurb": "Skiing by day, proper Spanish food and wine by night. Tapas beats a bar snack every time.",
                "piste_km": 160,
                "runs_green": 6,
                "runs_blue": 36,
                "runs_red": 29,
                "runs_black": 7,
                "lifts": 33,
                "altitude_top_m": 2610,
                "altitude_base_m": 1500,
                "things_to_do": ["Baqueira's renowned mountain-hut restaurants (a favourite of the Spanish royal family)", "Aran Sky Spa wellness centre in the village", "Off-piste and freeride bowls on the Bonaigua/Cap de Baqueira sectors"],
                "official_url": "https://www.baqueira.es/en",
                "best_for": "Groups of friends, intermediates and those wanting a Pyrenean/Spanish alternative to the Alps",
            },
            {
                "name": "Alta Badia, Italy",
                "budget": "high",
                "blurb": "Some of the best on-mountain dining anywhere in the Alps, deep in South Tyrol's food-obsessed corner of Italy.",
                "piste_km": 130,
                "runs_green": 8,
                "runs_blue": 68,
                "runs_red": 30,
                "runs_black": 5,
                "lifts": 52,
                "altitude_top_m": 2750,
                "altitude_base_m": 1324,
                "things_to_do": ["Sellaronda: ski the circuit around the Sella massif linking four valleys", "Michelin-starred mountain restaurants (Alta Badia has the highest concentration of gourmet rifugios in the Dolomites)", "Wellness/spa centres in Corvara and La Villa, plus horse-drawn sleigh rides"],
                "official_url": "https://www.altabadia.org/en",
                "best_for": "Families, couples and intermediates who enjoy fine dining and scenery",
            },
            {
                "name": "Serre Chevalier, France",
                "budget": "mid",
                "blurb": "A string of characterful old villages linked by lift, with proper regional cooking and mountain restaurants that take food as seriously as the skiing.",
                "piste_km": 250,
                "runs_green": 25,
                "runs_blue": 32,
                "runs_red": 42,
                "runs_black": 15,
                "lifts": 77,
                "altitude_top_m": 2800,
                "altitude_base_m": 1350,
                "things_to_do": ["Wood-fired mountain restaurants in the pine forests around Villeneuve/Monetier", "Thermal spa (Grands Bains du Monêtier) at the base of the resort", "Sledging/tobogganing runs and Le Bez/Villeneuve's traditional apres-ski bars"],
                "official_url": "https://www.serre-chevalier.com/en/",
                "best_for": "Families, intermediates and groups wanting varied, tree-lined skiing",
            },
            {
                "name": "Zakopane, Poland",
                "budget": "low",
                "blurb": "Poland's ski capital, and the food is the whole point: hearty, cheap, and served in wooden mountain huts that feel like they haven't changed in decades.",
                "piste_km": 25,
                "runs_green": 8,
                "runs_blue": 8,
                "runs_red": 3,
                "runs_black": 2,
                "lifts": 25,
                "altitude_top_m": 1987,
                "altitude_base_m": 704,
                "things_to_do": ["Zakopane's Krupówki Street: Poland's best-known mountain-resort promenade for shopping, bars and street food", "Thermal baths at Chochołowskie Termy or Bukovina Terma near Bialka Tatrzanska", "Kasprowy Wierch cable car to the summit for views into Slovakia, and horse-drawn sleigh rides in the Tatras"],
                "official_url": "https://www.pkl.pl/en/kasprowy-wierch",
                "best_for": "Beginners, families and budget-conscious groups (small, low-altitude ski areas)",
            },
        ],
    },
}
